### ISSUE TITLE
Update all transformers to use `get_feature_names_out()` instead of `get_feature_names()`

### ISSUE THREAD

**Issue by rubenpeters91** [RoyalHaskoningDHV/sam#27]
sklearn has deprecated `get_feature_names()` in favor of `get_feature_names_out()` this is blocking when updating to a new sklearn version, so we should update these functions, the behaviour stays the same

**Comment by rubenpeters91** [comment]
Also check if `get_feature_names_out()` will work for Pipelines that contain Simple

**Comment by abontsema** [comment]
Resolved by #43 and #42
