### ISSUE TITLE
Decide on model naming conventions

### ISSUE THREAD

**Issue by abontsema** [RoyalHaskoningDHV/sam#29]
SAmQuantileMLP / TimeseriesMLP or something different?

Option 1: *TimeseriesRegressor
BaseTimeseriesRegressor
ConstantTimeseriesRegressor
LinearTimeseriesRegressor
MLPTimeseriesRegressor

Option 2:*QuantileForecaster
BaseQuantileForecaster
ConstantQuantileForecaster
LinearQuantileForecaster
MLPQuantileForecaster

Other suggestions are welcome.

**Comment by rubenpeters91** [comment]
We chose option 1

**Comment by abontsema** [comment]
Resolved by #45 and #42
