### ISSUE TITLE
Update documentation for release

### ISSUE THREAD

**Issue by rubenpeters91** [RoyalHaskoningDHV/sam#32]
We should update the documentation for release and also fix the autodoc functionality, since currently it seems broken on: https://sam-rhdhv.readthedocs.io/en/latest/

- [x] Move important information from General documents to a new "Introduction" section
- [x] Remove General documents section
- [x] Replace example notebooks with the new examples
- [x] Fix autodoc errors so the docs work on readthedocs
- [x] Fix tensorflow import so autodocs works for metrics, models and visualization

**Comment by abontsema** [comment]
Resolved by #46 and #42
